project:
  type: website
  output-dir: docs
  resources:
    - "assets/*"
website:
  page-footer: |
    This public service announcement provided by [rob salmond](rob@progredo.ca), copyright 2024 progredo systems inc.
